# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export PNPM_HOME="$HOME/Library/pnpm"
export DENO_INSTALL="$HOME/.deno"
export BUN_INSTALL="$HOME/.bun"
export PYENV_ROOT="$HOME/.pyenv"

if command -v hx >/dev/null; then
    export EDITOR=hx
    export VISUAL=hx
else
    export EDITOR=vim
    export VISUAL=vim
fi

export PAGER=less
export LESS="-F -g -i -M -R -S -w -X -z-4"
export LANG="en_US.UTF-8"

. "$HOME/.cargo/env"
