#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# load autocompletions
fpath=(~/.zsh $fpath)
autoload -Uz compinit
compinit -u

if command -v nvim >/dev/null; then
    alias vim=nvim
    alias vi=nvim
fi

if command -v hx >/dev/null; then
    export EDITOR=hx
    export VISUAL=hx
else
    export EDITOR=vim
    export VISUAL=vim
fi

export PAGER=less
export LESS="-F -g -i -M -R -S -w -X -z-4"
export LANG="en_US.UTF-8"

# pnpm
export PNPM_HOME="/Users/christianrotzoll/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"

# deno
export DENO_INSTALL="/Users/christianrotzoll/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"

# bun
[ -s "/Users/christianrotzoll/.bun/_bun" ] && source "/Users/christianrotzoll/.bun/_bun"
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# zls for zig lsp
export PATH="$HOME/development/zls/zig-out/bin:$PATH"

# golang bin dir on path
export PATH="$HOME/go/bin:$PATH"

[ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"
